server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: person-management-AWS-challenge

  datasource:
    url: jdbc:postgresql://database-aws-challenge.ccfoiu2kkm6k.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Admin.1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect